# The optimizationBenchmarking.org tool suite is a Java Project
language: java

# By default, it runs under Java 7
jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8
    
# Cache Maven dependencies to speed up builds.
cache:
  directories:
  - $HOME/.m2
  
# load base project
before_install:
  - chmod 755 "buildDependencies.sh"
  - "./buildDependencies.sh" 
    
# custom build step
script: mvn -C -B compile package test install